// generated by build_blog.py from ../presentation/deck_data.js
window.SCENES = {
 "Part2_VanillaFails": [
  [
   {
    "src": "media/Part2_VanillaFails/00_autocreated.mp4",
    "dur": 3.8
   }
  ],
  [
   {
    "src": "media/Part2_VanillaFails/01_case1-shallow-deep.mp4",
    "dur": 3.6
   }
  ],
  [
   {
    "src": "media/Part2_VanillaFails/02_case2-same.mp4",
    "dur": 1.6
   }
  ],
  [
   {
    "src": "media/Part2_VanillaFails/03_case3-reversed.mp4",
    "dur": 1.6
   }
  ],
  [
   {
    "src": "media/Part2_VanillaFails/04_token-axis.mp4",
    "dur": 4.2
   }
  ],
  [
   {
    "src": "media/Part2_VanillaFails/05_second-hop-unused.mp4",
    "dur": 3.0
   }
  ],
  [
   {
    "src": "media/Part2_VanillaFails/06_bridge.mp4",
    "dur": 2.8
   }
  ],
  [
   {
    "src": "media/Part2_VanillaFails/07_miss-layer5.mp4",
    "dur": 1.9
   }
  ],
  [
   {
    "src": "media/Part2_VanillaFails/08_miss-layer6.mp4",
    "dur": 3.0
   }
  ],
  [
   {
    "src": "media/Part2_VanillaFails/09_fact-left-behind.mp4",
    "dur": 2.7
   }
  ],
  [
   {
    "src": "media/Part2_VanillaFails/10_depth-local.mp4",
    "dur": 1.6
   }
  ]
 ],
 "Part3_LoopedTransformer": [
  [
   {
    "src": "media/Part3_LoopedTransformer/00_autocreated.mp4",
    "dur": 3.6
   }
  ],
  [
   {
    "src": "media/Part3_LoopedTransformer/01_fold.mp4",
    "dur": 3.4
   }
  ],
  [
   {
    "src": "media/Part3_LoopedTransformer/02_two-loops.mp4",
    "dur": 3.5
   }
  ],
  [
   {
    "src": "media/Part3_LoopedTransformer/03_equation.mp4",
    "dur": 4.1
   }
  ],
  [
   {
    "src": "media/Part3_LoopedTransformer/04_token-axis.mp4",
    "dur": 3.6
   }
  ],
  [
   {
    "src": "media/Part3_LoopedTransformer/05_loop1-pass.mp4",
    "dur": 1.9
   }
  ],
  [
   {
    "src": "media/Part3_LoopedTransformer/06_loop1-bridge.mp4",
    "dur": 2.6
   }
  ],
  [
   {
    "src": "media/Part3_LoopedTransformer/07_loop2-pass.mp4",
    "dur": 1.9
   }
  ],
  [
   {
    "src": "media/Part3_LoopedTransformer/08_loop2-answer.mp4",
    "dur": 3.8
   }
  ],
  [
   {
    "src": "media/Part3_LoopedTransformer/09_same-memory.mp4",
    "dur": 2.3
   }
  ]
 ],
 "Part4A_Stage1": [
  [
   {
    "src": "media/Part4A_Stage1/00_model.mp4",
    "dur": 4.95
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/01_loops.mp4",
    "dur": 2.8
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/02_read-carol.mp4",
    "dur": 3.2
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/03_verdict-carol.mp4",
    "dur": 2.3
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/04_stage1.mp4",
    "dur": 1.4
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/05_read-eve.mp4",
    "dur": 3.2
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/06_verdict-eve.mp4",
    "dur": 2.7
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/07_atomic.mp4",
    "dur": 1.9
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/08_read-bob.mp4",
    "dur": 3.2
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/09_verdict-bob.mp4",
    "dur": 2.7
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/10_table1a.mp4",
    "dur": 1.8
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/11_stage1-bars.mp4",
    "dur": 1.8
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/12_stage2-bars.mp4",
    "dur": 1.8
   }
  ],
  [
   {
    "src": "media/Part4A_Stage1/13_one-hop.mp4",
    "dur": 1.2
   }
  ]
 ],
 "Part4B_Bridge": [
  [
   {
    "src": "media/Part4B_Bridge/00_setup.mp4",
    "dur": 4.65
   }
  ],
  [
   {
    "src": "media/Part4B_Bridge/01_loop1.mp4",
    "dur": 1.6
   }
  ],
  [
   {
    "src": "media/Part4B_Bridge/02_ring-bridge.mp4",
    "dur": 1.2
   }
  ],
  [
   {
    "src": "media/Part4B_Bridge/03_logits.mp4",
    "dur": 3.1
   }
  ],
  [
   {
    "src": "media/Part4B_Bridge/04_softmax.mp4",
    "dur": 2.0
   }
  ],
  [
   {
    "src": "media/Part4B_Bridge/05_table1b.mp4",
    "dur": 1.9
   }
  ],
  [
   {
    "src": "media/Part4B_Bridge/06_decodable.mp4",
    "dur": 1.2
   }
  ]
 ],
 "Part4C_Mismatch": [
  [
   {
    "src": "media/Part4C_Mismatch/00_hidden-state.mp4",
    "dur": 1.5
   }
  ],
  [
   {
    "src": "media/Part4C_Mismatch/01_vs-embedding.mp4",
    "dur": 2.4
   }
  ],
  [
   {
    "src": "media/Part4C_Mismatch/02_readout-chain.mp4",
    "dur": 1.8
   }
  ],
  [
   {
    "src": "media/Part4C_Mismatch/03_shift-c.mp4",
    "dur": 1.7
   }
  ],
  [
   {
    "src": "media/Part4C_Mismatch/04_softmax-invariant.mp4",
    "dur": 2.4
   }
  ],
  [
   {
    "src": "media/Part4C_Mismatch/05_two-spaces.mp4",
    "dur": 1.6
   }
  ],
  [
   {
    "src": "media/Part4C_Mismatch/06_far-apart.mp4",
    "dur": 1.3
   }
  ],
  [
   {
    "src": "media/Part4C_Mismatch/07_same-readout.mp4",
    "dur": 1.3
   }
  ],
  [
   {
    "src": "media/Part4C_Mismatch/08_cosine-vectors.mp4",
    "dur": 2.4
   }
  ],
  [
   {
    "src": "media/Part4C_Mismatch/09_cosine-table.mp4",
    "dur": 1.1
   }
  ],
  [
   {
    "src": "media/Part4C_Mismatch/10_not-equal.mp4",
    "dur": 1.4
   }
  ]
 ],
 "Part4D_Intervention": [
  [
   {
    "src": "media/Part4D_Intervention/00_diagram.mp4",
    "dur": 5.85
   }
  ],
  [
   {
    "src": "media/Part4D_Intervention/01_eq3.mp4",
    "dur": 2.5
   }
  ],
  [
   {
    "src": "media/Part4D_Intervention/02_mix.mp4",
    "dur": 1.2
   }
  ],
  [
   {
    "src": "media/Part4D_Intervention/03_loop2.mp4",
    "dur": 1.4
   }
  ],
  [
   {
    "src": "media/Part4D_Intervention/04_chart.mp4",
    "dur": 1.6
   }
  ],
  [
   {
    "src": "media/Part4D_Intervention/05_sweep.mp4",
    "dur": 1.9
   }
  ],
  [
   {
    "src": "media/Part4D_Intervention/06_conclusion.mp4",
    "dur": 1.2
   }
  ]
 ],
 "Part5A_DiscoLoop": [
  [
   {
    "src": "media/Part5A_DiscoLoop/00_proposal.mp4",
    "dur": 2.6
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/01_name.mp4",
    "dur": 3.4
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/02_diagram.mp4",
    "dur": 3.3
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/03_ring-bridge.mp4",
    "dur": 2.1
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/04_decode.mp4",
    "dur": 2.1
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/05_softmax.mp4",
    "dur": 1.4
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/06_encode.mp4",
    "dur": 1.6
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/07_weighted-sum.mp4",
    "dur": 3.0
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/08_norm-gate.mp4",
    "dur": 3.833
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/09_add-back.mp4",
    "dur": 2.8
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/10_back-loop.mp4",
    "dur": 1.5
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/11_phi-box.mp4",
    "dur": 2.2
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/12_phi-chain.mp4",
    "dur": 5.3
   }
  ],
  [
   {
    "src": "media/Part5A_DiscoLoop/13_eq5.mp4",
    "dur": 2.8
   }
  ]
 ],
 "Part5B_EveryPosition": [
  [
   {
    "src": "media/Part5B_EveryPosition/00_phi-every.mp4",
    "dur": 3.0
   }
  ],
  [
   {
    "src": "media/Part5B_EveryPosition/01_inject-all.mp4",
    "dur": 4.867
   }
  ],
  [
   {
    "src": "media/Part5B_EveryPosition/02_eq4-init.mp4",
    "dur": 2.1
   }
  ],
  [
   {
    "src": "media/Part5B_EveryPosition/03_eq4-loop.mp4",
    "dur": 1.6
   }
  ],
  [
   {
    "src": "media/Part5B_EveryPosition/04_eq4-update.mp4",
    "dur": 4.0
   }
  ]
 ],
 "Part5C_Gate": [
  [
   {
    "src": "media/Part5C_Gate/00_gate-alpha.mp4",
    "dur": 4.5
   }
  ],
  [
   {
    "src": "media/Part5C_Gate/01_fixed.mp4",
    "dur": 2.8
   }
  ],
  [
   {
    "src": "media/Part5C_Gate/02_learnable.mp4",
    "dur": 1.3
   }
  ],
  [
   {
    "src": "media/Part5C_Gate/03_token-gates.mp4",
    "dur": 3.1
   }
  ],
  [
   {
    "src": "media/Part5C_Gate/04_last-loop.mp4",
    "dur": 2.5
   }
  ]
 ],
 "Part6A_Symbolic": [
  [
   {
    "src": "media/Part6A_Symbolic/00_axes.mp4",
    "dur": 2.0
   }
  ],
  [
   {
    "src": "media/Part6A_Symbolic/01_curves.mp4",
    "dur": 3.4
   }
  ],
  [
   {
    "src": "media/Part6A_Symbolic/02_recap.mp4",
    "dur": 3.5
   }
  ],
  [
   {
    "src": "media/Part6A_Symbolic/03_one-loop.mp4",
    "dur": 2.3
   }
  ],
  [
   {
    "src": "media/Part6A_Symbolic/04_match-target.mp4",
    "dur": 1.6
   }
  ],
  [
   {
    "src": "media/Part6A_Symbolic/05_stage1-curves.mp4",
    "dur": 4.6
   }
  ],
  [
   {
    "src": "media/Part6A_Symbolic/06_band-memorize.mp4",
    "dur": 2.2
   }
  ],
  [
   {
    "src": "media/Part6A_Symbolic/07_decompose.mp4",
    "dur": 1.3
   }
  ],
  [
   {
    "src": "media/Part6A_Symbolic/08_caption.mp4",
    "dur": 1.8
   }
  ]
 ],
 "Part6B_Language": [
  [
   {
    "src": "media/Part6B_Language/00_vocab.mp4",
    "dur": 4.6
   }
  ],
  [
   {
    "src": "media/Part6B_Language/01_atomic-fact.mp4",
    "dur": 3.3
   }
  ],
  [
   {
    "src": "media/Part6B_Language/02_direct.mp4",
    "dur": 2.6
   }
  ],
  [
   {
    "src": "media/Part6B_Language/03_reverse.mp4",
    "dur": 1.7
   }
  ],
  [
   {
    "src": "media/Part6B_Language/04_answer.mp4",
    "dur": 1.1
   }
  ],
  [
   {
    "src": "media/Part6B_Language/05_fig4.mp4",
    "dur": 5.2
   }
  ]
 ],
 "Part6C_Pretraining": [
  [
   {
    "src": "media/Part6C_Pretraining/00_setting.mp4",
    "dur": 5.1
   }
  ],
  [
   {
    "src": "media/Part6C_Pretraining/01_loss-curves.mp4",
    "dur": 5.2
   }
  ],
  [
   {
    "src": "media/Part6C_Pretraining/02_zoom.mp4",
    "dur": 3.9
   }
  ],
  [
   {
    "src": "media/Part6C_Pretraining/03_crossover.mp4",
    "dur": 2.0
   }
  ],
  [
   {
    "src": "media/Part6C_Pretraining/04_table.mp4",
    "dur": 2.2
   }
  ]
 ],
 "Part7A_LengthGen": [
  [
   {
    "src": "media/Part7A_LengthGen/00_autocreated.mp4",
    "dur": 1.4
   }
  ],
  [
   {
    "src": "media/Part7A_LengthGen/01_train-setup.mp4",
    "dur": 1.6
   }
  ],
  [
   {
    "src": "media/Part7A_LengthGen/02_one-hop.mp4",
    "dur": 2.7
   }
  ],
  [
   {
    "src": "media/Part7A_LengthGen/03_two-hop.mp4",
    "dur": 3.0
   }
  ],
  [
   {
    "src": "media/Part7A_LengthGen/04_test-three-hop.mp4",
    "dur": 1.7
   }
  ],
  [
   {
    "src": "media/Part7A_LengthGen/05_plus-one-loop.mp4",
    "dur": 1.8
   }
  ],
  [
   {
    "src": "media/Part7A_LengthGen/06_run-three-loops.mp4",
    "dur": 2.5
   }
  ],
  [
   {
    "src": "media/Part7A_LengthGen/07_test-time-scaling.mp4",
    "dur": 1.1
   }
  ]
 ],
 "Part7B_ScalableLoops": [
  [
   {
    "src": "media/Part7B_ScalableLoops/00_autocreated.mp4",
    "dur": 1.9
   }
  ],
  [
   {
    "src": "media/Part7B_ScalableLoops/01_more-loops.mp4",
    "dur": 3.6
   }
  ],
  [
   {
    "src": "media/Part7B_ScalableLoops/02_compute-axis.mp4",
    "dur": 1.2
   }
  ],
  [
   {
    "src": "media/Part7B_ScalableLoops/03_deep-graph.mp4",
    "dur": 3.3
   }
  ],
  [
   {
    "src": "media/Part7B_ScalableLoops/04_hard-to-optimize.mp4",
    "dur": 1.7
   }
  ],
  [
   {
    "src": "media/Part7B_ScalableLoops/05_standard.mp4",
    "dur": 4.0
   }
  ],
  [
   {
    "src": "media/Part7B_ScalableLoops/06_sps-tokens.mp4",
    "dur": 2.0
   }
  ],
  [
   {
    "src": "media/Part7B_ScalableLoops/07_sps-forward.mp4",
    "dur": 2.0
   }
  ],
  [
   {
    "src": "media/Part7B_ScalableLoops/08_legend.mp4",
    "dur": 1.2
   }
  ],
  [
   {
    "src": "media/Part7B_ScalableLoops/09_question.mp4",
    "dur": 1.4
   }
  ]
 ],
 "Scene1_Example": [
  [
   {
    "src": "media/Scene1_Example/00_autocreated.mp4",
    "dur": 1.6
   }
  ],
  [
   {
    "src": "media/Scene1_Example/01_fact1.mp4",
    "dur": 2.1
   }
  ],
  [
   {
    "src": "media/Scene1_Example/02_fact2.mp4",
    "dur": 2.1
   }
  ],
  [
   {
    "src": "media/Scene1_Example/03_question.mp4",
    "dur": 1.4
   }
  ],
  [
   {
    "src": "media/Scene1_Example/04_compose.mp4",
    "dur": 1.8
   }
  ],
  [
   {
    "src": "media/Scene1_Example/05_answer.mp4",
    "dur": 2.7
   }
  ],
  [
   {
    "src": "media/Scene1_Example/06_bridge.mp4",
    "dur": 1.1
   }
  ]
 ],
 "Scene2_Abstraction": [
  [
   {
    "src": "media/Scene2_Abstraction/00_autocreated.mp4",
    "dur": 4.1
   }
  ],
  [
   {
    "src": "media/Scene2_Abstraction/01_atomic-fact.mp4",
    "dur": 5.0
   }
  ],
  [
   {
    "src": "media/Scene2_Abstraction/02_two-hop.mp4",
    "dur": 5.7
   }
  ],
  [
   {
    "src": "media/Scene2_Abstraction/03_bridge-hidden.mp4",
    "dur": 3.2
   }
  ],
  [
   {
    "src": "media/Scene2_Abstraction/04_kg-relabel.mp4",
    "dur": 3.9
   }
  ],
  [
   {
    "src": "media/Scene2_Abstraction/05_kg-grow.mp4",
    "dur": 3.6
   }
  ]
 ],
 "Scene3_Splits": [
  [
   {
    "src": "media/Scene3_Splits/00_autocreated.mp4",
    "dur": 4.3
   }
  ],
  [
   {
    "src": "media/Scene3_Splits/01_shared-rels.mp4",
    "dur": 5.2
   }
  ],
  [
   {
    "src": "media/Scene3_Splits/02_train-atom.mp4",
    "dur": 4.0
   }
  ],
  [
   {
    "src": "media/Scene3_Splits/03_all-atoms.mp4",
    "dur": 3.0
   }
  ],
  [
   {
    "src": "media/Scene3_Splits/04_train-id.mp4",
    "dur": 3.4
   }
  ],
  [
   {
    "src": "media/Scene3_Splits/05_no-ood-train.mp4",
    "dur": 3.2
   }
  ],
  [
   {
    "src": "media/Scene3_Splits/06_test-id.mp4",
    "dur": 5.4
   }
  ],
  [
   {
    "src": "media/Scene3_Splits/07_test-ood.mp4",
    "dur": 3.8
   }
  ]
 ],
 "Slide7_LoopVsNoLoop": [
  [
   {
    "src": "media/Slide7_LoopVsNoLoop/00_autocreated.mp4",
    "dur": 2.0
   }
  ],
  [
   {
    "src": "media/Slide7_LoopVsNoLoop/01_curves.mp4",
    "dur": 4.9
   }
  ],
  [
   {
    "src": "media/Slide7_LoopVsNoLoop/02_table.mp4",
    "dur": 1.9
   }
  ],
  [
   {
    "src": "media/Slide7_LoopVsNoLoop/03_ood-low.mp4",
    "dur": 1.3
   }
  ],
  [
   {
    "src": "media/Slide7_LoopVsNoLoop/04_question.mp4",
    "dur": 1.2
   }
  ]
 ]
};
window.SCENE_OUTS = {
 "Part2_VanillaFails": [],
 "Part3_LoopedTransformer": [],
 "Part4A_Stage1": [
  {
   "src": "media/Part4A_Stage1/14_out.mp4",
   "dur": 0.8
  }
 ],
 "Part4B_Bridge": [
  {
   "src": "media/Part4B_Bridge/07_out.mp4",
   "dur": 1.1
  }
 ],
 "Part4C_Mismatch": [
  {
   "src": "media/Part4C_Mismatch/11_out.mp4",
   "dur": 0.8
  }
 ],
 "Part4D_Intervention": [],
 "Part5A_DiscoLoop": [
  {
   "src": "media/Part5A_DiscoLoop/14_out.mp4",
   "dur": 0.8
  }
 ],
 "Part5B_EveryPosition": [],
 "Part5C_Gate": [
  {
   "src": "media/Part5C_Gate/05_out.mp4",
   "dur": 0.8
  }
 ],
 "Part6A_Symbolic": [
  {
   "src": "media/Part6A_Symbolic/09_out.mp4",
   "dur": 0.8
  }
 ],
 "Part6B_Language": [
  {
   "src": "media/Part6B_Language/06_out.mp4",
   "dur": 0.8
  }
 ],
 "Part6C_Pretraining": [
  {
   "src": "media/Part6C_Pretraining/05_out.mp4",
   "dur": 0.8
  }
 ],
 "Part7A_LengthGen": [
  {
   "src": "media/Part7A_LengthGen/08_out.mp4",
   "dur": 0.8
  }
 ],
 "Part7B_ScalableLoops": [
  {
   "src": "media/Part7B_ScalableLoops/10_out.mp4",
   "dur": 0.8
  }
 ],
 "Scene1_Example": [],
 "Scene2_Abstraction": [],
 "Scene3_Splits": [],
 "Slide7_LoopVsNoLoop": []
};
