// generated by build_deck.py from the sectioned Manim renders (1080p60)
window.DECK = {
 "Part2_VanillaFails": [
  {
   "src": "media/Part2_VanillaFails/00_autocreated.mp4",
   "name": "autocreated",
   "dur": 3.8
  },
  {
   "src": "media/Part2_VanillaFails/01_case1-shallow-deep.mp4",
   "name": "case1-shallow-deep",
   "dur": 3.6
  },
  {
   "src": "media/Part2_VanillaFails/02_case2-same.mp4",
   "name": "case2-same",
   "dur": 1.6
  },
  {
   "src": "media/Part2_VanillaFails/03_case3-reversed.mp4",
   "name": "case3-reversed",
   "dur": 1.6
  },
  {
   "src": "media/Part2_VanillaFails/04_token-axis.mp4",
   "name": "token-axis",
   "dur": 4.2
  },
  {
   "src": "media/Part2_VanillaFails/05_second-hop-unused.mp4",
   "name": "second-hop-unused",
   "dur": 3.0
  },
  {
   "src": "media/Part2_VanillaFails/06_bridge.mp4",
   "name": "bridge",
   "dur": 2.8
  },
  {
   "src": "media/Part2_VanillaFails/07_miss-layer5.mp4",
   "name": "miss-layer5",
   "dur": 1.9
  },
  {
   "src": "media/Part2_VanillaFails/08_miss-layer6.mp4",
   "name": "miss-layer6",
   "dur": 3.0
  },
  {
   "src": "media/Part2_VanillaFails/09_fact-left-behind.mp4",
   "name": "fact-left-behind",
   "dur": 2.7
  },
  {
   "src": "media/Part2_VanillaFails/10_depth-local.mp4",
   "name": "depth-local",
   "dur": 1.6
  }
 ],
 "Part3_LoopedTransformer": [
  {
   "src": "media/Part3_LoopedTransformer/00_autocreated.mp4",
   "name": "autocreated",
   "dur": 3.6
  },
  {
   "src": "media/Part3_LoopedTransformer/01_fold.mp4",
   "name": "fold",
   "dur": 3.4
  },
  {
   "src": "media/Part3_LoopedTransformer/02_two-loops.mp4",
   "name": "two-loops",
   "dur": 3.5
  },
  {
   "src": "media/Part3_LoopedTransformer/03_equation.mp4",
   "name": "equation",
   "dur": 4.1
  },
  {
   "src": "media/Part3_LoopedTransformer/04_token-axis.mp4",
   "name": "token-axis",
   "dur": 3.6
  },
  {
   "src": "media/Part3_LoopedTransformer/05_loop1-pass.mp4",
   "name": "loop1-pass",
   "dur": 1.9
  },
  {
   "src": "media/Part3_LoopedTransformer/06_loop1-bridge.mp4",
   "name": "loop1-bridge",
   "dur": 2.6
  },
  {
   "src": "media/Part3_LoopedTransformer/07_loop2-pass.mp4",
   "name": "loop2-pass",
   "dur": 1.9
  },
  {
   "src": "media/Part3_LoopedTransformer/08_loop2-answer.mp4",
   "name": "loop2-answer",
   "dur": 3.8
  },
  {
   "src": "media/Part3_LoopedTransformer/09_same-memory.mp4",
   "name": "same-memory",
   "dur": 2.3
  }
 ],
 "Part4A_Stage1": [
  {
   "src": "media/Part4A_Stage1/00_model.mp4",
   "name": "model",
   "dur": 4.95
  },
  {
   "src": "media/Part4A_Stage1/01_loops.mp4",
   "name": "loops",
   "dur": 2.8
  },
  {
   "src": "media/Part4A_Stage1/02_read-carol.mp4",
   "name": "read-carol",
   "dur": 3.2
  },
  {
   "src": "media/Part4A_Stage1/03_verdict-carol.mp4",
   "name": "verdict-carol",
   "dur": 2.3
  },
  {
   "src": "media/Part4A_Stage1/04_stage1.mp4",
   "name": "stage1",
   "dur": 1.4
  },
  {
   "src": "media/Part4A_Stage1/05_read-eve.mp4",
   "name": "read-eve",
   "dur": 3.2
  },
  {
   "src": "media/Part4A_Stage1/06_verdict-eve.mp4",
   "name": "verdict-eve",
   "dur": 2.7
  },
  {
   "src": "media/Part4A_Stage1/07_atomic.mp4",
   "name": "atomic",
   "dur": 1.9
  },
  {
   "src": "media/Part4A_Stage1/08_read-bob.mp4",
   "name": "read-bob",
   "dur": 3.2
  },
  {
   "src": "media/Part4A_Stage1/09_verdict-bob.mp4",
   "name": "verdict-bob",
   "dur": 2.7
  },
  {
   "src": "media/Part4A_Stage1/10_table1a.mp4",
   "name": "table1a",
   "dur": 1.8
  },
  {
   "src": "media/Part4A_Stage1/11_stage1-bars.mp4",
   "name": "stage1-bars",
   "dur": 1.8
  },
  {
   "src": "media/Part4A_Stage1/12_stage2-bars.mp4",
   "name": "stage2-bars",
   "dur": 1.8
  },
  {
   "src": "media/Part4A_Stage1/13_one-hop.mp4",
   "name": "one-hop",
   "dur": 1.2
  },
  {
   "src": "media/Part4A_Stage1/14_out.mp4",
   "name": "out",
   "dur": 0.8
  }
 ],
 "Part4B_Bridge": [
  {
   "src": "media/Part4B_Bridge/00_setup.mp4",
   "name": "setup",
   "dur": 4.65
  },
  {
   "src": "media/Part4B_Bridge/01_loop1.mp4",
   "name": "loop1",
   "dur": 1.6
  },
  {
   "src": "media/Part4B_Bridge/02_ring-bridge.mp4",
   "name": "ring-bridge",
   "dur": 1.2
  },
  {
   "src": "media/Part4B_Bridge/03_logits.mp4",
   "name": "logits",
   "dur": 3.1
  },
  {
   "src": "media/Part4B_Bridge/04_softmax.mp4",
   "name": "softmax",
   "dur": 2.0
  },
  {
   "src": "media/Part4B_Bridge/05_table1b.mp4",
   "name": "table1b",
   "dur": 1.9
  },
  {
   "src": "media/Part4B_Bridge/06_decodable.mp4",
   "name": "decodable",
   "dur": 1.2
  },
  {
   "src": "media/Part4B_Bridge/07_out.mp4",
   "name": "out",
   "dur": 1.1
  }
 ],
 "Part4C_Mismatch": [
  {
   "src": "media/Part4C_Mismatch/00_hidden-state.mp4",
   "name": "hidden-state",
   "dur": 1.5
  },
  {
   "src": "media/Part4C_Mismatch/01_vs-embedding.mp4",
   "name": "vs-embedding",
   "dur": 2.4
  },
  {
   "src": "media/Part4C_Mismatch/02_readout-chain.mp4",
   "name": "readout-chain",
   "dur": 1.8
  },
  {
   "src": "media/Part4C_Mismatch/03_shift-c.mp4",
   "name": "shift-c",
   "dur": 1.7
  },
  {
   "src": "media/Part4C_Mismatch/04_softmax-invariant.mp4",
   "name": "softmax-invariant",
   "dur": 2.4
  },
  {
   "src": "media/Part4C_Mismatch/05_two-spaces.mp4",
   "name": "two-spaces",
   "dur": 1.6
  },
  {
   "src": "media/Part4C_Mismatch/06_far-apart.mp4",
   "name": "far-apart",
   "dur": 1.3
  },
  {
   "src": "media/Part4C_Mismatch/07_same-readout.mp4",
   "name": "same-readout",
   "dur": 1.3
  },
  {
   "src": "media/Part4C_Mismatch/08_cosine-vectors.mp4",
   "name": "cosine-vectors",
   "dur": 2.4
  },
  {
   "src": "media/Part4C_Mismatch/09_cosine-table.mp4",
   "name": "cosine-table",
   "dur": 1.1
  },
  {
   "src": "media/Part4C_Mismatch/10_not-equal.mp4",
   "name": "not-equal",
   "dur": 1.4
  },
  {
   "src": "media/Part4C_Mismatch/11_out.mp4",
   "name": "out",
   "dur": 0.8
  }
 ],
 "Part4D_Intervention": [
  {
   "src": "media/Part4D_Intervention/00_diagram.mp4",
   "name": "diagram",
   "dur": 5.85
  },
  {
   "src": "media/Part4D_Intervention/01_eq3.mp4",
   "name": "eq3",
   "dur": 2.5
  },
  {
   "src": "media/Part4D_Intervention/02_mix.mp4",
   "name": "mix",
   "dur": 1.2
  },
  {
   "src": "media/Part4D_Intervention/03_loop2.mp4",
   "name": "loop2",
   "dur": 1.4
  },
  {
   "src": "media/Part4D_Intervention/04_chart.mp4",
   "name": "chart",
   "dur": 1.6
  },
  {
   "src": "media/Part4D_Intervention/05_sweep.mp4",
   "name": "sweep",
   "dur": 1.9
  },
  {
   "src": "media/Part4D_Intervention/06_conclusion.mp4",
   "name": "conclusion",
   "dur": 1.2
  }
 ],
 "Part5A_DiscoLoop": [
  {
   "src": "media/Part5A_DiscoLoop/00_proposal.mp4",
   "name": "proposal",
   "dur": 2.6
  },
  {
   "src": "media/Part5A_DiscoLoop/01_name.mp4",
   "name": "name",
   "dur": 3.4
  },
  {
   "src": "media/Part5A_DiscoLoop/02_diagram.mp4",
   "name": "diagram",
   "dur": 3.3
  },
  {
   "src": "media/Part5A_DiscoLoop/03_ring-bridge.mp4",
   "name": "ring-bridge",
   "dur": 2.1
  },
  {
   "src": "media/Part5A_DiscoLoop/04_decode.mp4",
   "name": "decode",
   "dur": 2.1
  },
  {
   "src": "media/Part5A_DiscoLoop/05_softmax.mp4",
   "name": "softmax",
   "dur": 1.4
  },
  {
   "src": "media/Part5A_DiscoLoop/06_encode.mp4",
   "name": "encode",
   "dur": 1.6
  },
  {
   "src": "media/Part5A_DiscoLoop/07_weighted-sum.mp4",
   "name": "weighted-sum",
   "dur": 3.0
  },
  {
   "src": "media/Part5A_DiscoLoop/08_norm-gate.mp4",
   "name": "norm-gate",
   "dur": 3.833
  },
  {
   "src": "media/Part5A_DiscoLoop/09_add-back.mp4",
   "name": "add-back",
   "dur": 2.8
  },
  {
   "src": "media/Part5A_DiscoLoop/10_back-loop.mp4",
   "name": "back-loop",
   "dur": 1.5
  },
  {
   "src": "media/Part5A_DiscoLoop/11_phi-box.mp4",
   "name": "phi-box",
   "dur": 2.2
  },
  {
   "src": "media/Part5A_DiscoLoop/12_phi-chain.mp4",
   "name": "phi-chain",
   "dur": 5.3
  },
  {
   "src": "media/Part5A_DiscoLoop/13_eq5.mp4",
   "name": "eq5",
   "dur": 2.8
  },
  {
   "src": "media/Part5A_DiscoLoop/14_out.mp4",
   "name": "out",
   "dur": 0.8
  }
 ],
 "Part5B_EveryPosition": [
  {
   "src": "media/Part5B_EveryPosition/00_phi-every.mp4",
   "name": "phi-every",
   "dur": 3.0
  },
  {
   "src": "media/Part5B_EveryPosition/01_inject-all.mp4",
   "name": "inject-all",
   "dur": 4.867
  },
  {
   "src": "media/Part5B_EveryPosition/02_eq4-init.mp4",
   "name": "eq4-init",
   "dur": 2.1
  },
  {
   "src": "media/Part5B_EveryPosition/03_eq4-loop.mp4",
   "name": "eq4-loop",
   "dur": 1.6
  },
  {
   "src": "media/Part5B_EveryPosition/04_eq4-update.mp4",
   "name": "eq4-update",
   "dur": 4.0
  }
 ],
 "Part5C_Gate": [
  {
   "src": "media/Part5C_Gate/00_gate-alpha.mp4",
   "name": "gate-alpha",
   "dur": 4.5
  },
  {
   "src": "media/Part5C_Gate/01_fixed.mp4",
   "name": "fixed",
   "dur": 2.8
  },
  {
   "src": "media/Part5C_Gate/02_learnable.mp4",
   "name": "learnable",
   "dur": 1.3
  },
  {
   "src": "media/Part5C_Gate/03_token-gates.mp4",
   "name": "token-gates",
   "dur": 3.1
  },
  {
   "src": "media/Part5C_Gate/04_last-loop.mp4",
   "name": "last-loop",
   "dur": 2.5
  },
  {
   "src": "media/Part5C_Gate/05_out.mp4",
   "name": "out",
   "dur": 0.8
  }
 ],
 "Part6A_Symbolic": [
  {
   "src": "media/Part6A_Symbolic/00_axes.mp4",
   "name": "axes",
   "dur": 2.0
  },
  {
   "src": "media/Part6A_Symbolic/01_curves.mp4",
   "name": "curves",
   "dur": 3.4
  },
  {
   "src": "media/Part6A_Symbolic/02_recap.mp4",
   "name": "recap",
   "dur": 3.5
  },
  {
   "src": "media/Part6A_Symbolic/03_one-loop.mp4",
   "name": "one-loop",
   "dur": 2.3
  },
  {
   "src": "media/Part6A_Symbolic/04_match-target.mp4",
   "name": "match-target",
   "dur": 1.6
  },
  {
   "src": "media/Part6A_Symbolic/05_stage1-curves.mp4",
   "name": "stage1-curves",
   "dur": 4.6
  },
  {
   "src": "media/Part6A_Symbolic/06_band-memorize.mp4",
   "name": "band-memorize",
   "dur": 2.2
  },
  {
   "src": "media/Part6A_Symbolic/07_decompose.mp4",
   "name": "decompose",
   "dur": 1.3
  },
  {
   "src": "media/Part6A_Symbolic/08_caption.mp4",
   "name": "caption",
   "dur": 1.8
  },
  {
   "src": "media/Part6A_Symbolic/09_out.mp4",
   "name": "out",
   "dur": 0.8
  }
 ],
 "Part6B_Language": [
  {
   "src": "media/Part6B_Language/00_vocab.mp4",
   "name": "vocab",
   "dur": 4.6
  },
  {
   "src": "media/Part6B_Language/01_atomic-fact.mp4",
   "name": "atomic-fact",
   "dur": 3.3
  },
  {
   "src": "media/Part6B_Language/02_direct.mp4",
   "name": "direct",
   "dur": 2.6
  },
  {
   "src": "media/Part6B_Language/03_reverse.mp4",
   "name": "reverse",
   "dur": 1.7
  },
  {
   "src": "media/Part6B_Language/04_answer.mp4",
   "name": "answer",
   "dur": 1.1
  },
  {
   "src": "media/Part6B_Language/05_fig4.mp4",
   "name": "fig4",
   "dur": 5.2
  },
  {
   "src": "media/Part6B_Language/06_out.mp4",
   "name": "out",
   "dur": 0.8
  }
 ],
 "Part6C_Pretraining": [
  {
   "src": "media/Part6C_Pretraining/00_setting.mp4",
   "name": "setting",
   "dur": 5.1
  },
  {
   "src": "media/Part6C_Pretraining/01_loss-curves.mp4",
   "name": "loss-curves",
   "dur": 5.2
  },
  {
   "src": "media/Part6C_Pretraining/02_zoom.mp4",
   "name": "zoom",
   "dur": 3.9
  },
  {
   "src": "media/Part6C_Pretraining/03_crossover.mp4",
   "name": "crossover",
   "dur": 2.0
  },
  {
   "src": "media/Part6C_Pretraining/04_table.mp4",
   "name": "table",
   "dur": 2.2
  },
  {
   "src": "media/Part6C_Pretraining/05_out.mp4",
   "name": "out",
   "dur": 0.8
  }
 ],
 "Part7A_LengthGen": [
  {
   "src": "media/Part7A_LengthGen/00_autocreated.mp4",
   "name": "autocreated",
   "dur": 1.4
  },
  {
   "src": "media/Part7A_LengthGen/01_train-setup.mp4",
   "name": "train-setup",
   "dur": 1.6
  },
  {
   "src": "media/Part7A_LengthGen/02_one-hop.mp4",
   "name": "one-hop",
   "dur": 2.7
  },
  {
   "src": "media/Part7A_LengthGen/03_two-hop.mp4",
   "name": "two-hop",
   "dur": 3.0
  },
  {
   "src": "media/Part7A_LengthGen/04_test-three-hop.mp4",
   "name": "test-three-hop",
   "dur": 1.7
  },
  {
   "src": "media/Part7A_LengthGen/05_plus-one-loop.mp4",
   "name": "plus-one-loop",
   "dur": 1.8
  },
  {
   "src": "media/Part7A_LengthGen/06_run-three-loops.mp4",
   "name": "run-three-loops",
   "dur": 2.5
  },
  {
   "src": "media/Part7A_LengthGen/07_test-time-scaling.mp4",
   "name": "test-time-scaling",
   "dur": 1.1
  },
  {
   "src": "media/Part7A_LengthGen/08_out.mp4",
   "name": "out",
   "dur": 0.8
  }
 ],
 "Part7B_ScalableLoops": [
  {
   "src": "media/Part7B_ScalableLoops/00_autocreated.mp4",
   "name": "autocreated",
   "dur": 1.9
  },
  {
   "src": "media/Part7B_ScalableLoops/01_more-loops.mp4",
   "name": "more-loops",
   "dur": 3.6
  },
  {
   "src": "media/Part7B_ScalableLoops/02_compute-axis.mp4",
   "name": "compute-axis",
   "dur": 1.2
  },
  {
   "src": "media/Part7B_ScalableLoops/03_deep-graph.mp4",
   "name": "deep-graph",
   "dur": 3.3
  },
  {
   "src": "media/Part7B_ScalableLoops/04_hard-to-optimize.mp4",
   "name": "hard-to-optimize",
   "dur": 1.7
  },
  {
   "src": "media/Part7B_ScalableLoops/05_standard.mp4",
   "name": "standard",
   "dur": 4.0
  },
  {
   "src": "media/Part7B_ScalableLoops/06_sps-tokens.mp4",
   "name": "sps-tokens",
   "dur": 2.0
  },
  {
   "src": "media/Part7B_ScalableLoops/07_sps-forward.mp4",
   "name": "sps-forward",
   "dur": 2.0
  },
  {
   "src": "media/Part7B_ScalableLoops/08_legend.mp4",
   "name": "legend",
   "dur": 1.2
  },
  {
   "src": "media/Part7B_ScalableLoops/09_question.mp4",
   "name": "question",
   "dur": 1.4
  },
  {
   "src": "media/Part7B_ScalableLoops/10_out.mp4",
   "name": "out",
   "dur": 0.8
  }
 ],
 "Scene1_Example": [
  {
   "src": "media/Scene1_Example/00_autocreated.mp4",
   "name": "autocreated",
   "dur": 1.6
  },
  {
   "src": "media/Scene1_Example/01_fact1.mp4",
   "name": "fact1",
   "dur": 2.1
  },
  {
   "src": "media/Scene1_Example/02_fact2.mp4",
   "name": "fact2",
   "dur": 2.1
  },
  {
   "src": "media/Scene1_Example/03_question.mp4",
   "name": "question",
   "dur": 1.4
  },
  {
   "src": "media/Scene1_Example/04_compose.mp4",
   "name": "compose",
   "dur": 1.8
  },
  {
   "src": "media/Scene1_Example/05_answer.mp4",
   "name": "answer",
   "dur": 2.7
  },
  {
   "src": "media/Scene1_Example/06_bridge.mp4",
   "name": "bridge",
   "dur": 1.1
  }
 ],
 "Scene2_Abstraction": [
  {
   "src": "media/Scene2_Abstraction/00_autocreated.mp4",
   "name": "autocreated",
   "dur": 4.1
  },
  {
   "src": "media/Scene2_Abstraction/01_atomic-fact.mp4",
   "name": "atomic-fact",
   "dur": 5.0
  },
  {
   "src": "media/Scene2_Abstraction/02_two-hop.mp4",
   "name": "two-hop",
   "dur": 5.7
  },
  {
   "src": "media/Scene2_Abstraction/03_bridge-hidden.mp4",
   "name": "bridge-hidden",
   "dur": 3.2
  },
  {
   "src": "media/Scene2_Abstraction/04_kg-relabel.mp4",
   "name": "kg-relabel",
   "dur": 3.9
  },
  {
   "src": "media/Scene2_Abstraction/05_kg-grow.mp4",
   "name": "kg-grow",
   "dur": 3.6
  }
 ],
 "Scene3_Splits": [
  {
   "src": "media/Scene3_Splits/00_autocreated.mp4",
   "name": "autocreated",
   "dur": 4.3
  },
  {
   "src": "media/Scene3_Splits/01_shared-rels.mp4",
   "name": "shared-rels",
   "dur": 5.2
  },
  {
   "src": "media/Scene3_Splits/02_train-atom.mp4",
   "name": "train-atom",
   "dur": 4.0
  },
  {
   "src": "media/Scene3_Splits/03_all-atoms.mp4",
   "name": "all-atoms",
   "dur": 3.0
  },
  {
   "src": "media/Scene3_Splits/04_train-id.mp4",
   "name": "train-id",
   "dur": 3.4
  },
  {
   "src": "media/Scene3_Splits/05_no-ood-train.mp4",
   "name": "no-ood-train",
   "dur": 3.2
  },
  {
   "src": "media/Scene3_Splits/06_test-id.mp4",
   "name": "test-id",
   "dur": 5.4
  },
  {
   "src": "media/Scene3_Splits/07_test-ood.mp4",
   "name": "test-ood",
   "dur": 3.8
  }
 ],
 "Slide7_LoopVsNoLoop": [
  {
   "src": "media/Slide7_LoopVsNoLoop/00_autocreated.mp4",
   "name": "autocreated",
   "dur": 2.0
  },
  {
   "src": "media/Slide7_LoopVsNoLoop/01_curves.mp4",
   "name": "curves",
   "dur": 4.9
  },
  {
   "src": "media/Slide7_LoopVsNoLoop/02_table.mp4",
   "name": "table",
   "dur": 1.9
  },
  {
   "src": "media/Slide7_LoopVsNoLoop/03_ood-low.mp4",
   "name": "ood-low",
   "dur": 1.3
  },
  {
   "src": "media/Slide7_LoopVsNoLoop/04_question.mp4",
   "name": "question",
   "dur": 1.2
  }
 ],
 "Slide_Conclusion": [
  {
   "src": "media/Slide_Conclusion/00_autocreated.mp4",
   "name": "autocreated",
   "dur": 1.4
  },
  {
   "src": "media/Slide_Conclusion/01_takeaway-1.mp4",
   "name": "takeaway-1",
   "dur": 1.4
  },
  {
   "src": "media/Slide_Conclusion/02_takeaway-2.mp4",
   "name": "takeaway-2",
   "dur": 1.4
  }
 ]
};
